{{- if .Values.hfTokenSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-hf.hfTokenSecretName" . }}
  labels:
    {{- include "vllm-hf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.hfTokenSecret.key }}: {{ .Values.hfTokenSecret.token | quote }}
{{- end }}
{{- if .Values.apiKeySecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-hf.apiKeySecretName" . }}
  labels:
    {{- include "vllm-hf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKeySecret.key }}: {{ .Values.apiKeySecret.value | quote }}
{{- end }}
